name: dart_vlc
description: Flutter media playback, broadcast, recording & chromecast library. Based on libvlc.
version: 0.2.0
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  dart_vlc_ffi: any
  path: ">=1.8.0 <2.0.0"
  path_provider: ">=2.0.2 <3.0.0"
  audio_video_progress_bar: ">=0.9.0 <1.0.0"
  flutter_native_view:
    git:
      url: https://github.com/alexmercerind/flutter_native_view.git
      ref: 832dcf3dc0974edafd7dac592f703b260aeff502

# REMOVE THIS BEFORE PUBLISHING ON pub.dev.
dependency_overrides:
  dart_vlc_ffi:
    path: ./ffi

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
      macos:
        pluginClass: DartVlcPlugin
      ios:
        pluginClass: DartVlcPlugin
