name: Github Actions
on: [push, pull_request]

defaults:
  run:
    working-directory: example

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --verbose
      - uses: actions/upload-artifact@v1
        with:
          name: dart_vlc_example
          path: example/build/windows/runner/Release

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: sudo apt update
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev vlc libvlc-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux --verbose

  build_macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos --verbose
